class DirectionCalculator

  @red_line    = ["LAMBERT MAIN TRML METROLINK STATION", "LAMBERT EAST TRML METROLINK STATION", 
                  "NORTH HANLEY METROLINK STATION", "UMSL NORTH METROLINK STATION", "UMSL SOUTH METROLINK STATION", 
                  "ROCK ROAD METROLINK STATION", "WELLSTON METROLINK STATION", "DELMAR METROLINK STATION", 
                  "FOREST PARK METROLINK STATION", "CENTRAL WEST END METROLINK STATION", "GRAND METROLINK STATION", 
                  "UNION STA METROLINK STATION", "CIVIC CENTER METROLINK STATION", "STADIUM METROLINK STATION", 
                  "8TH AND PINE METROLINK STATION", "CONVENTION CENTER METROLINK STATION", "ARCH LACLEDES METROLINK STATION", 
                  "EAST RIVERFRONT METROLINK STATION", "5TH & MISSOURI METROLINK STATION", "EMERSON PARK METROLINK STATION", 
                  "JJK CENTER METROLINK STATION", "WASHINGTON PARK METROLINK STATION", "FAIRVIEW HEIGHTS METROLINK STATION", 
                  "MEMORIAL HOSPITAL METROLINK STATION", "SWANSEA METROLINK STATION", "BELLEVILLE METROLINK STATION"]
                  "COLLEGE METROLINK STATION", "SHILOH-SCOTT METROLINK STATION"]

  @blue_line   = ["SHREWSBURY METROLINK STATION", "SUNNEN METROLINK STATION", "MAPLEWOOD METROLINK STATION", 
                  "BRENTWOOD METROLINK STATION", "RICHMOND HEIGHTS METROLINK STATION", "CLAYTON METROLINK STATION", 
                  "FORSYTH METROLINK STATION", "U CITY BIG BEND METROLINK  STATION", "SKINKER METROLINK STATION", 
                  "FOREST PARK METROLINK STATION", "CENTRAL WEST END METROLINK STATION", "GRAND METROLINK STATION", 
                  "UNION STA METROLINK STATION", "CIVIC CENTER METROLINK STATION", "STADIUM METROLINK STATION", 
                  "8TH AND PINE METROLINK STATION", "CONVENTION CENTER METROLINK STATION", "ARCH LACLEDES METROLINK STATION", 
                  "EAST RIVERFRONT METROLINK STATION", "5TH & MISSOURI METROLINK STATION", "EMERSON PARK METROLINK STATION", 
                  "JJK CENTER METROLINK STATION", "WASHINGTON PARK METROLINK STATION", "FAIRVIEW HEIGHTS METROLINK STATION"]

  @purple_line = ["FOREST PARK METROLINK STATION", "CENTRAL WEST END METROLINK STATION", "GRAND METROLINK STATION", 
                  "UNION STA METROLINK STATION", "CIVIC CENTER METROLINK STATION", "STADIUM METROLINK STATION", 
                  "8TH AND PINE METROLINK STATION", "CONVENTION CENTER METROLINK STATION", "ARCH LACLEDES METROLINK STATION", 
                  "EAST RIVERFRONT METROLINK STATION", "5TH & MISSOURI METROLINK STATION", "EMERSON PARK METROLINK STATION", 
                  "JJK CENTER METROLINK STATION", "WASHINGTON PARK METROLINK STATION", "FAIRVIEW HEIGHTS METROLINK STATION"]


  EASTBOUND = 0
  WESTBOUND = 1

  # pass in two stations, return direction, line taken
  # red, purple, blue, switch && 0 or 1

  if @purple.include?(stop1) && purple.include?(stop2)
    line = "purple"
  elsif @red_line.include?(stop1) && @red_line.include?(stop2)
    line = "red"
  end
  

  # model not inherit activerecord
  # set up rspec tests

end
